## Clean the Data

In [66]:
import pandas as pd
from pathlib import Path

import numpy as np

In [ ]:
options_path = "../data/options_data.csv"
options = pd.read_csv(options_path)

In [68]:
options = options.iloc[:, :7]

In [69]:
options

,symbol,strike,iv,last_price,expiry,type,underlying_price
0,AAPL US 02/20/26 C100 Equity,100.0,48.212910,164.07,2/20/2026,Call,263.878
1,AAPL US 02/20/26 C120 Equity,120.0,39.131880,144.14,2/20/2026,Call,263.810
2,AAPL US 02/20/26 C125 Equity,125.0,35.424600,138.90,2/20/2026,Call,263.810
3,AAPL US 02/20/26 C140 Equity,140.0,32.060450,124.25,2/20/2026,Call,263.800
4,AAPL US 02/20/26 C145 Equity,145.0,31.392700,115.02,2/20/2026,Call,263.810
...,...,...,...,...,...,...,...
11033,SPX US 08/21/26 C6400 Index,6400.0,0.215249,722.51,8/21/2026,Call,6903.360
11034,SPX US 08/21/26 C6425 Index,6425.0,0.213207,790.83,8/21/2026,Call,6902.210
11035,SPX US 08/21/26 C6450 Index,6450.0,0.211359,706.22,8/21/2026,Call,6903.250
11036,SPX US 08/21/26 C6475 Index,6475.0,0.209238,650.54,8/21/2026,Call,6903.170
11037,SPX US 08/21/26 C6500 Index,6500.0,0.207496,681.74,8/21/2026,Call,6903.250

In [70]:
options = options.dropna()

In [71]:
options

,symbol,strike,iv,last_price,expiry,type,underlying_price
0,AAPL US 02/20/26 C100 Equity,100.0,48.212910,164.07,2/20/2026,Call,263.878
1,AAPL US 02/20/26 C120 Equity,120.0,39.131880,144.14,2/20/2026,Call,263.810
2,AAPL US 02/20/26 C125 Equity,125.0,35.424600,138.90,2/20/2026,Call,263.810
3,AAPL US 02/20/26 C140 Equity,140.0,32.060450,124.25,2/20/2026,Call,263.800
4,AAPL US 02/20/26 C145 Equity,145.0,31.392700,115.02,2/20/2026,Call,263.810
...,...,...,...,...,...,...,...
11033,SPX US 08/21/26 C6400 Index,6400.0,0.215249,722.51,8/21/2026,Call,6903.360
11034,SPX US 08/21/26 C6425 Index,6425.0,0.213207,790.83,8/21/2026,Call,6902.210
11035,SPX US 08/21/26 C6450 Index,6450.0,0.211359,706.22,8/21/2026,Call,6903.250
11036,SPX US 08/21/26 C6475 Index,6475.0,0.209238,650.54,8/21/2026,Call,6903.170
11037,SPX US 08/21/26 C6500 Index,6500.0,0.207496,681.74,8/21/2026,Call,6903.250

In [72]:
options = options.rename(columns = {'equity':'symbol', 'volatil':'iv', 'last':'last_price', 'expire':'expiry', 'indicator':'type', 'underlying':'underlying_price'})

In [73]:
options

,symbol,strike,iv,last_price,expiry,type,underlying_price
0,AAPL US 02/20/26 C100 Equity,100.0,48.212910,164.07,2/20/2026,Call,263.878
1,AAPL US 02/20/26 C120 Equity,120.0,39.131880,144.14,2/20/2026,Call,263.810
2,AAPL US 02/20/26 C125 Equity,125.0,35.424600,138.90,2/20/2026,Call,263.810
3,AAPL US 02/20/26 C140 Equity,140.0,32.060450,124.25,2/20/2026,Call,263.800
4,AAPL US 02/20/26 C145 Equity,145.0,31.392700,115.02,2/20/2026,Call,263.810
...,...,...,...,...,...,...,...
11033,SPX US 08/21/26 C6400 Index,6400.0,0.215249,722.51,8/21/2026,Call,6903.360
11034,SPX US 08/21/26 C6425 Index,6425.0,0.213207,790.83,8/21/2026,Call,6902.210
11035,SPX US 08/21/26 C6450 Index,6450.0,0.211359,706.22,8/21/2026,Call,6903.250
11036,SPX US 08/21/26 C6475 Index,6475.0,0.209238,650.54,8/21/2026,Call,6903.170
11037,SPX US 08/21/26 C6500 Index,6500.0,0.207496,681.74,8/21/2026,Call,6903.250

In [ ]:
options.to_csv('../data/options_data.csv', index= False)

## Summary Statistics

In [75]:
options.describe()

             strike            iv    last_price  underlying_price
count  11038.000000  11038.000000  11038.000000      11038.000000
mean    3347.442245      1.184624    164.363912       3592.660858
std     3149.702893      4.208197    348.055722       3270.775777
min        5.000000      0.096421      0.010000        263.800000
25%      310.000000      0.217448      4.500000        409.765000
50%      950.000000      0.388346     50.870000        409.863800
75%     6620.000000      0.530018    186.000000       6902.910000
max    12400.000000     80.789500   5019.230000       6903.650000

In [76]:
options.shape

(11038, 7)

In [77]:
options.isna().sum()

symbol              0
strike              0
iv                  0
last_price          0
expiry              0
type                0
underlying_price    0
dtype: int64

In [78]:
options.dtypes

symbol               object
strike              float64
iv                  float64
last_price          float64
expiry               object
type                 object
underlying_price    float64
dtype: object

In [79]:
options['type'].value_counts()

type
Put     5800
Call    5238
Name: count, dtype: int64

In [80]:
options

,symbol,strike,iv,last_price,expiry,type,underlying_price
0,AAPL US 02/20/26 C100 Equity,100.0,48.212910,164.07,2/20/2026,Call,263.878
1,AAPL US 02/20/26 C120 Equity,120.0,39.131880,144.14,2/20/2026,Call,263.810
2,AAPL US 02/20/26 C125 Equity,125.0,35.424600,138.90,2/20/2026,Call,263.810
3,AAPL US 02/20/26 C140 Equity,140.0,32.060450,124.25,2/20/2026,Call,263.800
4,AAPL US 02/20/26 C145 Equity,145.0,31.392700,115.02,2/20/2026,Call,263.810
...,...,...,...,...,...,...,...
11033,SPX US 08/21/26 C6400 Index,6400.0,0.215249,722.51,8/21/2026,Call,6903.360
11034,SPX US 08/21/26 C6425 Index,6425.0,0.213207,790.83,8/21/2026,Call,6902.210
11035,SPX US 08/21/26 C6450 Index,6450.0,0.211359,706.22,8/21/2026,Call,6903.250
11036,SPX US 08/21/26 C6475 Index,6475.0,0.209238,650.54,8/21/2026,Call,6903.170
11037,SPX US 08/21/26 C6500 Index,6500.0,0.207496,681.74,8/21/2026,Call,6903.250

In [81]:
options.groupby('expiry')['expiry'].value_counts()

expiry
1/15/2027      330
1/21/2028      296
10/16/2026      33
11/20/2026     356
12/15/2028     278
12/17/2027     372
12/18/2026     354
2/20/2026     1023
3/17/2028       93
3/19/2027      160
3/20/2026     1752
4/17/2026     1605
5/15/2026     1332
6/16/2028      197
6/17/2027      329
6/18/2026     1086
7/17/2026      780
8/21/2026      321
9/18/2026      341
Name: count, dtype: int64

In [82]:
conditions = [
    (options['type'] == 'Call') & (options['strike'] < options['underlying_price']),  # Call ITM
    (options['type'] == 'Call') & (options['strike'] > options['underlying_price']),  # Call OTM

    (options['type'] == 'Put') & (options['strike'] > options['underlying_price']),   # Put ITM
    (options['type'] == 'Put') & (options['strike'] < options['underlying_price'])    # Put OTM
]

choices = ['ITM', 'OTM', 'ITM', 'OTM']

options['moneyyyyy'] = np.select(conditions, choices)

print(pd.crosstab(options['type'], options['moneyyyyy']))

moneyyyyy   ITM   OTM
type
Call       2461  2777
Put        1707  4093

In [83]:
options

,symbol,strike,iv,last_price,expiry,type,underlying_price,moneyyyyy
0,AAPL US 02/20/26 C100 Equity,100.0,48.212910,164.07,2/20/2026,Call,263.878,ITM
1,AAPL US 02/20/26 C120 Equity,120.0,39.131880,144.14,2/20/2026,Call,263.810,ITM
2,AAPL US 02/20/26 C125 Equity,125.0,35.424600,138.90,2/20/2026,Call,263.810,ITM
3,AAPL US 02/20/26 C140 Equity,140.0,32.060450,124.25,2/20/2026,Call,263.800,ITM
4,AAPL US 02/20/26 C145 Equity,145.0,31.392700,115.02,2/20/2026,Call,263.810,ITM
...,...,...,...,...,...,...,...,...
11033,SPX US 08/21/26 C6400 Index,6400.0,0.215249,722.51,8/21/2026,Call,6903.360,ITM
11034,SPX US 08/21/26 C6425 Index,6425.0,0.213207,790.83,8/21/2026,Call,6902.210,ITM
11035,SPX US 08/21/26 C6450 Index,6450.0,0.211359,706.22,8/21/2026,Call,6903.250,ITM
11036,SPX US 08/21/26 C6475 Index,6475.0,0.209238,650.54,8/21/2026,Call,6903.170,ITM
11037,SPX US 08/21/26 C6500 Index,6500.0,0.207496,681.74,8/21/2026,Call,6903.250,ITM

In [ ]:
options.to_csv('../data/options_data.csv', index = False)