In [ ]:
import pandas as pd

In [ ]:
options_path = "../data/options_data.csv"
options = pd.read_csv(options_path)

In [25]:
options = options.iloc[:, :7]

In [26]:
options

,equity,strike,volatil,last,expire,indicator,underlying
0,AAPL US 02/20/26 C100 Equity,100.0,4821.291,164.07,2/20/2026,Call,263.8780
1,AAPL US 02/20/26 C105 Equity,105.0,NaN,155.45,2/20/2026,Call,263.8181
2,AAPL US 02/20/26 C110 Equity,110.0,NaN,154.23,2/20/2026,Call,263.8100
3,AAPL US 02/20/26 C115 Equity,115.0,NaN,131.82,2/20/2026,Call,263.8000
4,AAPL US 02/20/26 C120 Equity,120.0,3913.188,144.14,2/20/2026,Call,263.8100
...,...,...,...,...,...,...,...
14797,SPX US 08/21/26 C6475 Index,6475.0,20.92385,650.54,8/21/2026,Call,6903.1700
14798,SPX US 08/21/26 C6480 Index,6480.0,20.91529,NaN,8/21/2026,Call,6902.1200
14799,SPX US 08/21/26 C6490 Index,6490.0,20.80261,NaN,8/21/2026,Call,6902.8700
14800,SPX US 08/21/26 C6500 Index,6500.0,20.74961,681.74,8/21/2026,Call,6903.2500
14801,SPX US 08/21/26 C6510 Index,6510.0,20.65544,NaN,8/21/2026,Call,6903.2500

In [27]:
options = options.dropna()

In [28]:
options

,equity,strike,volatil,last,expire,indicator,underlying
0,AAPL US 02/20/26 C100 Equity,100.0,4821.291,164.07,2/20/2026,Call,263.878
4,AAPL US 02/20/26 C120 Equity,120.0,3913.188,144.14,2/20/2026,Call,263.810
5,AAPL US 02/20/26 C125 Equity,125.0,3542.46,138.90,2/20/2026,Call,263.810
8,AAPL US 02/20/26 C140 Equity,140.0,3206.045,124.25,2/20/2026,Call,263.800
9,AAPL US 02/20/26 C145 Equity,145.0,3139.27,115.02,2/20/2026,Call,263.810
...,...,...,...,...,...,...,...
14788,SPX US 08/21/26 C6400 Index,6400.0,21.52491,722.51,8/21/2026,Call,6903.360
14791,SPX US 08/21/26 C6425 Index,6425.0,21.32066,790.83,8/21/2026,Call,6902.210
14794,SPX US 08/21/26 C6450 Index,6450.0,21.13585,706.22,8/21/2026,Call,6903.250
14797,SPX US 08/21/26 C6475 Index,6475.0,20.92385,650.54,8/21/2026,Call,6903.170
14800,SPX US 08/21/26 C6500 Index,6500.0,20.74961,681.74,8/21/2026,Call,6903.250

In [29]:
options = options.rename(columns = {'equity':'symbol', 'volatil':'iv', 'last':'last_price', 'expire':'expiry', 'indicator':'type', 'underlying':'underlying_price'})

In [30]:
options

,symbol,strike,iv,last_price,expiry,type,underlying_price
0,AAPL US 02/20/26 C100 Equity,100.0,4821.291,164.07,2/20/2026,Call,263.878
4,AAPL US 02/20/26 C120 Equity,120.0,3913.188,144.14,2/20/2026,Call,263.810
5,AAPL US 02/20/26 C125 Equity,125.0,3542.46,138.90,2/20/2026,Call,263.810
8,AAPL US 02/20/26 C140 Equity,140.0,3206.045,124.25,2/20/2026,Call,263.800
9,AAPL US 02/20/26 C145 Equity,145.0,3139.27,115.02,2/20/2026,Call,263.810
...,...,...,...,...,...,...,...
14788,SPX US 08/21/26 C6400 Index,6400.0,21.52491,722.51,8/21/2026,Call,6903.360
14791,SPX US 08/21/26 C6425 Index,6425.0,21.32066,790.83,8/21/2026,Call,6902.210
14794,SPX US 08/21/26 C6450 Index,6450.0,21.13585,706.22,8/21/2026,Call,6903.250
14797,SPX US 08/21/26 C6475 Index,6475.0,20.92385,650.54,8/21/2026,Call,6903.170
14800,SPX US 08/21/26 C6500 Index,6500.0,20.74961,681.74,8/21/2026,Call,6903.250

In [ ]:
options.to_csv('../data/options_data.csv', index= False)